### ISSUE TITLE
Price directive for empty account

### ISSUE THREAD

**Issue by tbm** [ghislainbourgeois/beancount_portfolio_allocation#3]
I'm not sure if it's worth addressing this issue. I have an account which has some stocks but later they are sold and the account is empty towards the end.  The script complains that there's no price directive for this stock but it doesn't matter since it's not there at the end.

I don't know how you do the calculation.  But why don't you only look at the balance of the accounts at the end?

```
ERROR:root:Could not get a value for currency NESTHIGHER in account Assets:Pension:NEST. Using 0. Are you missing a price directive?
```

**Comment by ghislainbourgeois** [comment]
The problem is that bean-query returns None instead of 0. Unless I re-implement the queries directly, I have no way of differentiating between a position that is down to 0 and a position that cannot be converted to a cash value because of a missing price. I will open an issue on beancount for this an keep this issue here to do a follow-up, but I am not sure when and if I will be able to fix this bug. 

The workaround right now is to make sure that at least one price directive is available for the commodities.

**Comment by ghislainbourgeois** [comment]
Upstream issue: https://bitbucket.org/blais/beancount/issues/312/bean-query-returns-none-instead-of-zero
